### ISSUE TITLE
Can't find H5Pset_dxpl_mpio, etc

### ISSUE THREAD

**Issue by yurivict** [llnl/mgmol#1]
clang-60 prints these errors on FreeBSD:
```
hdf_tools.cc:333:5: error: use of undeclared identifier 'H5Pset_dxpl_mpio'
    H5Pset_dxpl_mpio(plist_id, H5FD_MPIO_COLLECTIVE);
    ^
hdf_tools.cc:406:5: error: use of undeclared identifier 'H5Pset_dxpl_mpio'
    H5Pset_dxpl_mpio(plist_id, H5FD_MPIO_COLLECTIVE);
    ^
hdf_tools.cc:479:5: error: use of undeclared identifier 'H5Pset_dxpl_mpio'
    H5Pset_dxpl_mpio(plist_id, H5FD_MPIO_COLLECTIVE);
    ^
hdf_tools.cc:556:5: error: use of undeclared identifier 'H5Pset_dxpl_mpio'
    H5Pset_dxpl_mpio(plist_id, H5FD_MPIO_COLLECTIVE);
    ^
```

**Comment by jeanlucf22** [comment]
I have seen this type of error when trying to build with a non-parallel hdf5 library. MGmol requires the parallel version of hdf5.

**Comment by ptarey1952** [comment]
Yeah, that's right, instead of exporting CFLAGS like below for a serial version

export CFLAGS = -O -I../headers -I/apps/pkg/hdf5/1.10.5/gnu/include -DH5_USE_16_API

load the parallel HDF5 module (on clusters) and use the following 

export CFLAGS = -O -I../headers -I/apps/pkg/hdf5/1.10.5/mpi/include -DH5_USE_16_API

This is what our systems admin told me and it worked.
