### ISSUE TITLE
Problem with FindSCALAPACK and FindARPACK

### ISSUE THREAD

**Issue by Rombur** [llnl/mgmol#16]
Currently `FindSCALAPACK` is looking for a header file: either `scalapack.h` or  `mkl_scalapack.h` (see [here](https://github.com/LLNL/mgmol/blob/release/cmake_modules/FindSCALAPACK.cmake#L14)). While it makes sense to look for `mkl_scalapack.h` when using Intel Scalapack , I don't understand why you search for `scalapack.h`. Scalapack is a Fortran library so there are no header file. This creates a frustrating error when trying to configure MGmol since CMake will look for something that cannot exist. There is the same problem in  `FindARPACK`  where you check for `ARPACK.h` which does not exist.

@oseikuffuor1 it looks like you wrote that code, can you explain me how it is supposed to work. Thanks!

**Comment by oseikuffuor1** [comment]
Hi @Rombur, I agree with your comments above. I took a look again, and frankly, I am not sure why I included it there to begin with. I took a look back at my notes, and it is still not clear to me why. The initial cmake script was only working for intel so that is probably why I did not catch the frustrating errors. Sorry about that.
